<ADSWorkspace Revision="50" Version="100">
    <Workspace Name="">
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="dds.cfg" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Log Name="search_history.log" />
        <Preferences Name="ads_datacmps_lay.prf" />
        <Preferences Name="layout.prf" />
        <Preferences Name="project_system_lib_lay.prf" />
        <Preferences Name="schematic.prf" />
        <Dataset Name="Frequency_Transposer.ds" />
        <Dataset Name="LNA_test_1.ds" />
        <Dataset Name="LNA_test_3.ds" />
        <Dataset Name="test_board_AP.ds" />
        <Dataset Name="test_board_ideal_mixer.ds" />
        <Dataset Name="test_FilterUP.ds" />
        <Dataset Name="TEST_FILTRE_AFS.ds" />
        <Dataset Name="TEST_LNA.ds" />
        <Dataset Name="Test_PreFilterUP.ds" />
        <Dataset Name="test_s_param_ampli_LNA.ds" />
        <Dataset Name="Work_low_cost_VCO.ds" />
        <Data_Files Name="test_FilterUP.ds" />
        <Data_Files Name="test_board_ideal_mixer.ds" />
        <Data_Files Name="test_board_AP.ds" />
        <Data_Files Name="Work_low_cost_VCO.ds" />
        <Data_Files Name="test_s_param_ampli_LNA.ds" />
        <Data_Files Name="TEST_LNA.ds" />
        <Data_Files Name="Test_PreFilterUP.ds" />
        <Data_Files Name="LNA_test_1.ds" />
        <Data_Files Name="TEST_FILTRE_AFS.ds" />
        <Data_Files Name="LNA_test_3.ds" />
        <Data_Files Name="Frequency_Transposer.ds" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_sources" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_pelib" />
        <Library Name="ads_serdes_ref_channel" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_builtin" />
        <Library Name="ads_rflib" />
        <Library Name="ads_simulation" />
        <Library Name="ads_datacmps" />
        <Library Name="Simulation_Sequencing" />
        <Library Name="project_system_lib" />
        <Folder Name="Emilie&apos;s_default">
            <Cell Name="project_system_lib:Circulateur IN" />
            <Cell Name="project_system_lib:Circulateur OUT" />
            <Cell Name="project_system_lib:Filter DOWN" />
            <Cell Name="project_system_lib:Filter UP" />
            <Cell Name="project_system_lib:LNA" />
            <Cell Name="project_system_lib:Melangeur DOWN" />
            <Cell Name="project_system_lib:Melangeur UP" />
            <Cell Name="project_system_lib:PowerAmp" />
            <Cell Name="project_system_lib:Pre-Filter UP" />
        </Folder>
        <Folder Name="Test_Boards">
            <Data_Display Name="test_s_param_ampli_LNA.dds" />
            <Cell Name="project_system_lib:test_s_param_ampli_LNA" />
            <Cell Name="project_system_lib:Test_PreFilterUP" />
            <Data_Display Name="Test_PreFilterUP.dds" />
            <Cell Name="project_system_lib:TEST_FILTRE_AFS" />
            <Data_Display Name="TEST_FILTRE_AFS.dds" />
            <Data_Display Name="test_FilterUP.dds" />
            <Cell Name="project_system_lib:test_FilterUP" />
            <Data_Display Name="test_board_ideal_mixer.dds" />
            <Cell Name="project_system_lib:test_board_ideal_mixer" />
            <Data_Display Name="test_board_AP.dds" />
            <Cell Name="project_system_lib:test_board_AP" />
            <Cell Name="project_system_lib:test_board_LNA" />
            <Cell Name="project_system_lib:test_board_Inte_quartz" />
            <Cell Name="project_system_lib:test_board_LNA_ligne_transmission" />
            <Cell Name="project_system_lib:TEST_FILTRE_SF150868M4UU0" />
            <Cell Name="project_system_lib:test_board_Dual_Mixer_with_VCO" />
            <Cell Name="project_system_lib:test_board_Dual_Mixer_with_VCO_trans" />
            <Data_Display Name="test_board_Dual_Mixer_with_VCO.dds" />
            <Cell Name="project_system_lib:test_board_ideal_mixer2" />
            <Data_Display Name="test_board_ideal_mixer2.dds" />
            <Data_Display Name="test_board_Inte_quartz.dds" />
            <Data_Display Name="test_board_LNA.dds" />
            <Data_Display Name="test_board_LNA_ligne_transmission.dds" />
        </Folder>
        <Folder Name="Full_Module">
            <Cell Name="project_system_lib:Frequency_Transposer" />
            <Data_Display Name="Frequency_Transposer.dds" />
            <Cell Name="project_system_lib:Frequency_Transposer_Test_Board" />
            <Data_Display Name="Frequency_Transposer_Test_Board.dds" />
            <Cell Name="project_system_lib:Frequency_Transposer_Transmission_Line" />
            <Cell Name="project_system_lib:Frequency_Transposer_real" />
            <Data_Display Name="Frequency_Transposer_Transmission_Line.dds" />
        </Folder>
        <Folder Name="Component_Models">
            <Cell Name="project_system_lib:Work_low_cost_VCO" />
            <Data_Display Name="Work_low_cost_VCO.dds" />
            <Cell Name="project_system_lib:SYMB_Filtre_AFS869S3" />
            <Cell Name="project_system_lib:SYMB_Filtre_SF160868M4UU01" />
            <Cell Name="project_system_lib:Dual_Mixer_with_VCO" />
            <Cell Name="project_system_lib:Dual_Mixer_with_VCO_ideal" />
        </Folder>
        <Log Name="netlist.log" />
        <Dataset Name="Frequency_Transposer_Test_Board.ds" />
        <Data_Files Name="Frequency_Transposer_Test_Board.ds" />
        <Substrate Name="project_system_lib:tech.subst" />
        <Folder Name="Emilie&apos;s default with Transmission Line">
            <Cell Name="project_system_lib:Pre-Filter UP Transmission Line" />
            <Cell Name="project_system_lib:Circulateur IN Transmission Line" />
            <Cell Name="project_system_lib:Circulateur OUT Transmission Line" />
            <Cell Name="project_system_lib:PowerAmp Transmission Line" />
            <Cell Name="project_system_lib:Melangeur UP Transmission Line" />
            <Cell Name="project_system_lib:Melangeur DOWN Transmission Line" />
            <Cell Name="project_system_lib:Filter UP Transmission Line" />
            <Cell Name="project_system_lib:Filter DOWN Transmission Line" />
            <Cell Name="project_system_lib:LNA_GRF2070" />
            <Cell Name="project_system_lib:LNA_GRF2070_ligne_de_transmission" />
        </Folder>
        <Log Name="netlist.log" />
        <Dataset Name="TEST_FILTRE_SF150868M4UU0.ds" />
        <Data_Files Name="TEST_FILTRE_SF150868M4UU0.ds" />
        <Dataset Name="test_board_LNA_ligne_transmission.ds" />
        <Dataset Name="test_board_LNA_ligne_transmission_tune.ds" />
        <Data_Files Name="test_board_LNA_ligne_transmission.ds" />
        <Data_Files Name="test_board_LNA_ligne_transmission_tune.ds" />
        <Dataset Name="test_board_LNA.ds" />
        <Data_Files Name="dc_annotation\project_system_lib_%Frequency_%Transposer_%Test_%Board_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\project_system_lib_%Frequency_%Transposer_%Test_%Board_schematic\annotation_map.xml" />
        <Data_Files Name="Frequency_Transposer_Test_Board_data\logFile.txt" />
        <Data_Files Name="test_board_LNA_data\logFile.txt" />
        <Folder Name="Test_Adapt_Filter_down">
            <Cell Name="project_system_lib:Filter DOWN Transmission Line_v1" />
        </Folder>
        <Data_Files Name="test_board_LNA.ds" />
        <Data_Display Name="Filter DOWN Transmission Line_v1.dds" />
        <Preferences Name="ads_behavioral_lay.prf" />
        <Preferences Name="ads_rflib_lay.prf" />
        <Dataset Name="Filter_DOWN_Transmission_Line_v1.ds" />
        <Dataset Name="Frequency_Transposer_Transmission_Line.ds" />
        <Dataset Name="test_board_Inte_quartz.ds" />
        <Data_Files Name="dc_annotation\project_system_lib_%Frequency_%Transposer_%Transmission_%Line_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\project_system_lib_%Frequency_%Transposer_%Transmission_%Line_schematic\annotation_2.xml" />
        <Data_Files Name="dc_annotation\project_system_lib_%Frequency_%Transposer_%Transmission_%Line_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\project_system_lib_%L%N%A_test_1_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\project_system_lib_%L%N%A_test_1_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\project_system_lib_%Work_low_cost_%V%C%O_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\project_system_lib_%Work_low_cost_%V%C%O_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\project_system_lib_test_board_%A%P_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\project_system_lib_test_board_%A%P_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\project_system_lib_test_board_ideal_mixer_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\project_system_lib_test_board_ideal_mixer_schematic\annotation_map.xml" />
        <Data_Files Name="Filter_DOWN_Transmission_Line_v1.ds" />
        <Data_Files Name="Filter_DOWN_Transmission_Line_v1_data\logFile.txt" />
        <Data_Files Name="Frequency_Transposer_data\logFile.txt" />
        <Data_Files Name="Frequency_Transposer_Transmission_Line.ds" />
        <Data_Files Name="Frequency_Transposer_Transmission_Line_data\logFile.txt" />
        <Data_Files Name="LNA_test_1_data\logFile.txt" />
        <Data_Files Name="LNA_test_3_data\logFile.txt" />
        <Data_Files Name="test_board_AP_data\logFile.txt" />
        <Data_Files Name="test_board_ideal_mixer_data\logFile.txt" />
        <Data_Files Name="test_board_Inte_quartz.ds" />
        <Data_Files Name="test_board_Inte_quartz_data\logFile.txt" />
        <Data_Files Name="test_board_LNA_ligne_transmission_data\logFile.txt" />
        <Data_Files Name="test_board_LNA_ligne_transmission_tune_data\logFile.txt" />
        <Data_Files Name="test_FilterUP_data\logFile.txt" />
        <Data_Files Name="TEST_FILTRE_AFS_data\logFile.txt" />
        <Data_Files Name="TEST_FILTRE_SF150868M4UU0_data\logFile.txt" />
        <Data_Files Name="TEST_LNA_data\logFile.txt" />
        <Data_Files Name="test_s_param_ampli_LNA_data\logFile.txt" />
        <Data_Files Name="Work_low_cost_VCO_data\logFile.txt" />
        <Library Name="ads_quantum" />
        <Substrate Name="project_system_lib:substrate1.subst" />
        <Dataset Name="test_board_Dual_Mixer_with_VCO.ds" />
        <Data_Files Name="test_board_Dual_Mixer_with_VCO.ds" />
        <Data_Files Name="test_board_Dual_Mixer_with_VCO_data\logFile.txt" />
        <Data_Files Name="test_board_Dual_Mixer_with_VCO.fce" />
        <Data_Files Name="dc_annotation\project_system_lib_test_board_%Dual_%Mixer_with_%V%C%O_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\project_system_lib_test_board_%Dual_%Mixer_with_%V%C%O_schematic\annotation_2.xml" />
        <Data_Files Name="dc_annotation\project_system_lib_test_board_%Dual_%Mixer_with_%V%C%O_schematic\annotation_map.xml" />
        <Data_Files Name="test_board_ideal_mixer2_data\logFile.txt" />
        <Dataset Name="test_board_ideal_mixer2.ds" />
        <Data_Files Name="test_board_ideal_mixer2.ds" />
        <Data_Files Name="dc_annotation\project_system_lib_test_board_ideal_mixer2_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\project_system_lib_test_board_ideal_mixer2_schematic\annotation_2.xml" />
        <Data_Files Name="dc_annotation\project_system_lib_test_board_ideal_mixer2_schematic\annotation_map.xml" />
    </Workspace>
</ADSWorkspace>
