<ADSWorkspace Revision="17" Version="100">
    <Workspace Name="">
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="dds.cfg" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Log Name="search_history.log" />
        <Preferences Name="ads_datacmps_lay.prf" />
        <Preferences Name="layout.prf" />
        <Preferences Name="project_system_lib_lay.prf" />
        <Preferences Name="schematic.prf" />
        <Dataset Name="Frequency_Transposer.ds" />
        <Dataset Name="LNA_test_1.ds" />
        <Dataset Name="LNA_test_3.ds" />
        <Dataset Name="test_board_AP.ds" />
        <Dataset Name="test_board_ideal_mixer.ds" />
        <Dataset Name="test_FilterUP.ds" />
        <Dataset Name="TEST_FILTRE_AFS.ds" />
        <Dataset Name="TEST_LNA.ds" />
        <Dataset Name="Test_PreFilterUP.ds" />
        <Dataset Name="test_s_param_ampli_LNA.ds" />
        <Dataset Name="Work_low_cost_VCO.ds" />
        <Data_Files Name="dc_annotation/project_system_lib_%L%N%A_test_1_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/project_system_lib_%L%N%A_test_1_schematic/annotation_map.xml" />
        <Data_Files Name="dc_annotation/project_system_lib_test_board_ideal_mixer_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/project_system_lib_test_board_ideal_mixer_schematic/annotation_map.xml" />
        <Data_Files Name="dc_annotation/project_system_lib_%Work_low_cost_%V%C%O_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/project_system_lib_%Work_low_cost_%V%C%O_schematic/annotation_map.xml" />
        <Data_Files Name="dc_annotation/project_system_lib_%Frequency_%Transposer_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/project_system_lib_%Frequency_%Transposer_schematic/annotation_map.xml" />
        <Data_Files Name="dc_annotation/project_system_lib_test_board_%A%P_schematic/annotation_1.xml" />
        <Data_Files Name="dc_annotation/project_system_lib_test_board_%A%P_schematic/annotation_map.xml" />
        <Data_Files Name="Work_low_cost_VCO_data/logFile.txt" />
        <Data_Files Name="test_FilterUP.ds" />
        <Data_Files Name="test_board_ideal_mixer.ds" />
        <Data_Files Name="test_board_ideal_mixer_data/logFile.txt" />
        <Data_Files Name="test_FilterUP_data/logFile.txt" />
        <Data_Files Name="test_board_AP_data/logFile.txt" />
        <Data_Files Name="TEST_LNA_data/logFile.txt" />
        <Data_Files Name="test_board_AP.ds" />
        <Data_Files Name="Work_low_cost_VCO.ds" />
        <Data_Files Name="test_s_param_ampli_LNA_data/logFile.txt" />
        <Data_Files Name="test_s_param_ampli_LNA.ds" />
        <Data_Files Name="Frequency_Transposer_data/logFile.txt" />
        <Data_Files Name="TEST_FILTRE_AFS_data/logFile.txt" />
        <Data_Files Name="TEST_LNA.ds" />
        <Data_Files Name="Test_PreFilterUP.ds" />
        <Data_Files Name="LNA_test_1.ds" />
        <Data_Files Name="LNA_test_3_data/logFile.txt" />
        <Data_Files Name="TEST_FILTRE_AFS.ds" />
        <Data_Files Name="LNA_test_3.ds" />
        <Data_Files Name="LNA_test_1_data/logFile.txt" />
        <Data_Files Name="Frequency_Transposer.ds" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_sources" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_pelib" />
        <Library Name="ads_serdes_ref_channel" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_builtin" />
        <Library Name="ads_rflib" />
        <Library Name="ads_simulation" />
        <Library Name="ads_datacmps" />
        <Library Name="1xEV" />
        <Library Name="3GPPFDD" />
        <Library Name="3GPPFDD_10_99" />
        <Library Name="Antennas_and_Propagation" />
        <Library Name="CDMA" />
        <Library Name="cdma2000" />
        <Library Name="Circuit_Cosimulation" />
        <Library Name="CMMB" />
        <Library Name="Controllers" />
        <Library Name="DTMB" />
        <Library Name="DTV" />
        <Library Name="EDGE" />
        <Library Name="GSM" />
        <Library Name="HDL_Blocks" />
        <Library Name="HSDPA" />
        <Library Name="HSUPA" />
        <Library Name="Instruments" />
        <Library Name="Interactive_Controls_and_Displays" />
        <Library Name="LTE" />
        <Library Name="Numeric" />
        <Library Name="Obsolete" />
        <Library Name="Signal_Converters" />
        <Library Name="Simulation_Sequencing" />
        <Library Name="Sinks" />
        <Library Name="SystemVue_Cosimulation" />
        <Library Name="TDSCDMA" />
        <Library Name="Timed" />
        <Library Name="UMB" />
        <Library Name="UWB" />
        <Library Name="WLAN" />
        <Library Name="WLAN_11n" />
        <Library Name="WMAN" />
        <Library Name="WMAN_16e" />
        <Library Name="project_system_lib" />
        <Folder Name="Emilie&apos;s_default">
            <Cell Name="project_system_lib:Circulateur IN" />
            <Cell Name="project_system_lib:Circulateur OUT" />
            <Cell Name="project_system_lib:Filter DOWN" />
            <Cell Name="project_system_lib:Filter UP" />
            <Cell Name="project_system_lib:LNA" />
            <Cell Name="project_system_lib:Melangeur DOWN" />
            <Cell Name="project_system_lib:Melangeur UP" />
            <Cell Name="project_system_lib:PowerAmp" />
            <Cell Name="project_system_lib:Pre-Filter UP" />
        </Folder>
        <Folder Name="Test_Boards">
            <Cell Name="project_system_lib:LNA_test_1" />
            <Cell Name="project_system_lib:LNA_test_2" />
            <Cell Name="project_system_lib:LNA_test_3" />
            <Data_Display Name="LNA_test_3.dds" />
            <Cell Name="project_system_lib:LNA_test_4" />
            <Data_Display Name="test_s_param_ampli_LNA.dds" />
            <Cell Name="project_system_lib:test_s_param_ampli_LNA" />
            <Cell Name="project_system_lib:Test_PreFilterUP" />
            <Data_Display Name="Test_PreFilterUP.dds" />
            <Cell Name="project_system_lib:TEST_LNA" />
            <Data_Display Name="TEST_LNA.dds" />
            <Cell Name="project_system_lib:TEST_FILTRE_AFS" />
            <Data_Display Name="TEST_FILTRE_AFS.dds" />
            <Data_Display Name="test_FilterUP.dds" />
            <Cell Name="project_system_lib:test_FilterUP" />
            <Data_Display Name="test_board_ideal_mixer.dds" />
            <Cell Name="project_system_lib:test_board_ideal_mixer" />
            <Data_Display Name="test_board_AP.dds" />
            <Cell Name="project_system_lib:test_board_AP" />
        </Folder>
        <Folder Name="Full_Module">
            <Cell Name="project_system_lib:Frequency_Transposer" />
            <Data_Display Name="Frequency_Transposer.dds" />
        </Folder>
        <Folder Name="Component_Models">
            <Cell Name="project_system_lib:Work_low_cost_VCO" />
            <Data_Display Name="Work_low_cost_VCO.dds" />
            <Cell Name="project_system_lib:SYMB_Filtre_AFS869S3" />
        </Folder>
    </Workspace>
</ADSWorkspace>
